### ISSUE TITLE
Attachments

### ISSUE THREAD

**Issue by LincolnCraddock** [mucsci-students/2024fa-475-Amiga#25]
Implement attachment effects in attachment script
Each attachment script should inherit a child of Attachment (DefenseAttachment, AttackAttachment, SpecialAttachment)
Each attachment needs a prefab with its script and its sprite

**Comment by LincolnCraddock** [comment]
Attachments we want to implement:
Attack:
- Damage increase
- Multiple bullets per shot
- Faster moving bullet
- Larger bullet
- Increase bullet life (how long before it disappears)
- Increase how many times the bullet will bounce before disappearing
- Destroy terrain (extra attachments increase how far the debris is thrown)
Defense:
- Armor recovery increase
- Maximum armor increase
Special:
- Increase jump height
- Floating

Attachments we will consider implementing:
- Increase how many enemies the bullet can pierce before disappearing
  (this would conflict with the bullet bouncing attachment)
- Push / pull enemy

**Comment by DierF** [comment]
Not implemented:
Increase how many times the bullet will bounce before disappearing

Bullets destroy terrain
(extra attachments can increase how far the debris gets thrown when it is destroyed)

Increase how many enemies the bullet can pierce before disappearing
(this would conflict with the bullet bouncing attachment)

Push / pull enemy
